# 1. The address of our database vault (localhost door 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/crediguard

# 2. Database credentials configuration
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

